### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by JoaoManoelSilvaMorais** [GSTDiandre/ps2-discord-rpc#7]
Hello, I followed all the steps, but no response on Discord. I use a program called OPL Server that changes the HOST port, I don't know if that's relevant.

**Comment by GSTDiandre** [comment]
Hey, the SMB port shouldn't matter. Although I use Windows' own SMB sharing, I've tested the script with OPL Server on port 450 instead of the default 445 to confirm and it works all the same.

The script should set rich presence as soon as packets are read that match your console's IP address.

A couple troubleshooting steps:

- Ensure that you've created a Discord app with the same account you intend to use RPC with

- Check if your IPs and Client ID are set correctly in .env, surrounded by double quotes `"`. The host IP should match the Ethernet interface you're using to connect to the console.

- Run both `pip install` commands listed and check that you are receiving a `Requirement already satisfied` message.

If the log indicates that the PS2 is online but no status change occurs in discord, ensure that

![Screenshot](https://i.imgur.com/VNtOIfT.png)

is enabled in discord settings.

If none of these fix the issue, link your ``logs.log`` file.
